version: "3.8"
services:
  sub-store:
    image: xream/sub-store:latest
    container_name: sub-store
    ports:
      - "[2a0b:4e07:8:1::1:483]:3001:3001"  # 仅 IPv6
    restart: always
    volumes:
      - /opt/sub-store-data:/opt/app/data
    environment:
      - SUB_STORE_BACKEND_CRON=0 0 * * *
      - SUB_STORE_FRONTEND_BACKEND_PATH=/momobako
      - SUB_STORE_FRONTEND_HOST=0.0.0.0
      - SUB_STORE_FRONTEND_PORT=3001
      - SUB_STORE_DATA_BASE_PATH=/opt/app/data
      - SUB_STORE_BACKEND_API_HOST=0.0.0.0
      - SUB_STORE_BACKEND_API_PORT=3002
    stdin_open: true
    tty: true
